apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollama
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollama
  template:
    metadata:
      labels:
        app: rollama
    spec:
      containers:
      - name: rollama
        image: docker:5000/rollama:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
