apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollama-deployment
  labels:
    app: rollama
    environment: production
    version: SEMVER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollama
  template:
    metadata:
      labels:
        app: rollama
        verion: SEMVER
    spec:
      containers:
      - name: rollama
        image: docker:5000/rollama:SEMVER
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
