apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollama-deployment
  labels:
    app: rollama
    environment: production
    version: SEMVER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollama
  template:
    metadata:
      labels:
        app: rollama
        version: SEMVER
    spec:
      containers:
      - name: rollama
        image: jenkins-node-1:5000/rollama:SEMVER
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"
