--©2024, Ovais Quraishi
CREATE DATABASE rollama;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$
DECLARE
    generated_password TEXT;
BEGIN
    -- Generate the password and store it in the variable
    generated_password := encode(gen_random_bytes(20), 'base64');

    -- Check if the user already exists
    IF NOT EXISTS (SELECT 1 FROM pg_user WHERE usename = 'rollama') THEN
        -- Output the generated password
        RAISE NOTICE 'Generated password: %', generated_password;

        -- Create the user using the generated password
        EXECUTE format('CREATE USER rollama WITH PASSWORD %L', generated_password);
    ELSE
        RAISE NOTICE 'User "rollama" already exists. Skipping creation.';
    END IF;
END $$;

GRANT ALL PRIVILEGES ON DATABASE rollama TO rollama;
GRANT SELECT, insert ON ALL TABLES IN SCHEMA public TO rollama;

--Create Tables
CREATE TABLE IF NOT EXISTS authors (
    author_id VARCHAR PRIMARY KEY,
    author_name VARCHAR,
    author_created_utc INT
);

CREATE TABLE IF NOT EXISTS posts (
    post_id VARCHAR PRIMARY KEY,
    subreddit VARCHAR,
    post_author VARCHAR,
    post_title TEXT,
    post_body TEXT,
    post_created_utc INT,
    is_post_oc BOOLEAN,
    is_post_video BOOLEAN,
    post_upvote_count INTEGER,
    post_downvote_count INTEGER,
    subreddit_members INTEGER
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id VARCHAR PRIMARY KEY,
    comment_author VARCHAR,
    is_comment_submitter BOOLEAN,
    is_comment_edited TEXT,
    comment_created_utc INT,
    comment_body TEXT,
    post_id VARCHAR,
    subreddit TEXT
);

CREATE TABLE IF NOT EXISTS errors (
    item_id VARCHAR,
    item_type VARCHAR,
    error TEXT
);

CREATE TABLE IF NOT EXISTS subscription (
    datetimesubscribed VARCHAR,
    subreddit VARCHAR
);

CREATE TABLE IF NOT EXISTS analysis_documents (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    shasum_512 TEXT UNIQUE NOT NULL,
    analysis_document JSONB NOT NULL
);

--Create Indexes
--Analysis Documents
CREATE INDEX IF NOT EXISTS timestamp_index ON analysis_documents (timestamp);
CREATE INDEX IF NOT EXISTS shasum_512_index ON analysis_documents (shasum_512);
CREATE INDEX IF NOT EXISTS analysis_document_gin_index ON analysis_documents USING gin (
    analysis_document jsonb_path_ops
);
--Author
CREATE UNIQUE INDEX IF NOT EXISTS authors_pkey ON public.authors USING btree (
    authors_id
);
--Comment
CREATE UNIQUE INDEX IF NOT EXISTS comment_pkey ON public.comments USING btree (
    comment_id
);
CREATE INDEX IF NOT EXISTS comment_post_id_idx ON public.comments USING btree (
    post_id, subreddit
);
--Errors
CREATE INDEX IF NOT EXISTS errors_item_id_idx ON public.errors USING btree (
    item_id
);
--Posts
CREATE UNIQUE INDEX IF NOT EXISTS post_pkey ON public.posts USING btree (
    post_id
);
CREATE INDEX IF NOT EXISTS post_post_author_idx ON public.posts USING btree (
    post_author
);
CREATE INDEX IF NOT EXISTS post_subreddit_idx ON public.posts USING btree (
    subreddit
);
--Subscription
CREATE INDEX IF NOT EXISTS subscription_subreddit_idx ON public."subscription" (
    subreddit
);
CREATE INDEX idx_posts_post_id ON public.posts (post_id);
CREATE INDEX idx_analysis_documents_reference_id ON public.analysis_documents (
	(analysis_document->>'reference_id')
); 

