# Generated by Django 5.0.6 on 2024-05-09 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('analysis', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('schema_version', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_docs', to='posts.post')),
            ],
        ),
    ]
